name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/Pet-App-Project/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
          
      - name: Restore NuGet packages
        run: dotnet restore ./Gh.Actions.Poc/Gh.Actions.Poc.sln
      - name: Build and pack NuGet package
        run: |
          dotnet build ./Gh.Actions.Poc/Gh.Actions.Poc.sln --configuration Release 
          dotnet pack ./Gh.Actions.Poc/Gh.Actions.Poc.sln --configuration Release --output ./nupkg -p:PackageVersion=2.1.0

      - name: Publish NuGet package
        run: dotnet nuget push ./Gh.Actions.Poc/*.nupkg --skip-duplicate --no-symbols true

