name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test
      - name: Pack
        run: dotnet pack -c Release
        working-directory: ./MyProject
      - name: NuGet Push
        uses: nuget/push@v1
        with:
          nuget-api-key: ${{secrets.NUGET_API_KEY}}
          nuget-source: 'https://api.nuget.org/v3/index.json'
          path: './MyProject/bin/Release/*.nupkg'
